// packages/vue/src/app.vue
<template>
<article class="layout">
  <header class="header">
    <h1 class="header__title">JSON Editor for vue</h1>
  </header>
  <nav class="controller">
    <button type="button" @click="onClickChangeLive">Live({{state.live}})</button>
    <button type="button" @click="onClickChangeTheme">Theme({{state.theme}})</button>
    <button type="button" @click="onClickReplace">Replace</button>
    <button type="button" @click="onClickExport">Export</button>
    <button type="button" @click="onClickSelectNode">SelectNode</button>
  </nav>
  <div class="editor-body">
    <JsonEditor
      ref="$editor"
      :theme="state.theme"
      :live="state.live"
      @update="onUpdateEditor"/>
  </div>
</article>
</template>

<script setup>
import { reactive, ref, onMounted } from 'vue'
import JsonEditor from './json-editor/index.vue'
import '../../../src/json-editor/assets/main.scss'

const $editor = ref(null)
let editor
const state = reactive({
  live: true,
  theme: 'light',
})

function onClickChangeLive()
{
  state.live = !state.live
}

function onClickChangeTheme()
{
  switch (state.theme)
  {
    case 'system':
      state.theme = 'light'
      break
    case 'light':
      state.theme = 'dark'
      break
    case 'dark':
      state.theme = 'system'
      break
  }
}

function onUpdateEditor(src)
{
  console.warn('onUpdateEditor', src)
}

function onClickReplace()
{
  editor.replace({
    foo: 123123,
    bar: [ 8, 5, 3, null, false, true ],
    ooo: {
      q: 'qqq',
      w: 'www',
      e: null,
      r: true,
    },
  }, false)
}

function onClickExport()
{
  const result = editor.export(undefined, false, 2)
  console.warn('EXPORT:', result)
}

function onClickSelectNode()
{
  const node = editor.getNode('li.root')
  console.warn('SELECT NODE:', node)
  editor.import(node, { goo: 'se' }, false)
}

onMounted(() => {
  editor = $editor.value.core()
})
</script>

<style src="./app.scss" scoped></style>

// src/dev/app.svelte
<header>
  <h1>JSONEditor Development</h1>
</header>

<nav class="controller">
  <div class="controller__wrap">
    <button type="button" on:click={() => toktok(1)}>button #1</button>
    <button type="button" on:click={() => toktok(2)}>button #2</button>
    <button type="button" on:click={() => toktok(3)}>{theme}</button>
    <button type="button" on:click={exportData}>Export</button>
  </div>
</nav>

<div class="container">
  <json-editor
    bind:this={self}
    src={_data}
    live="true"
    theme={theme}/>
</div>

<script>
import { onMount } from 'svelte'
import JsonEditor from '../web-component.js'

let self
const elementName = 'json-editor'
let theme = 'system'
const data1 = {
  foo: 1,
  foo2: '1a1b1',
  foo3: false,
  foo44: [],
  foo4: [
    1, '2', null, true,
  ],
  foo5: {
    1: 11,
    22: '22',
    3: 33,
    44: null,
  },
}
const data2 = [
  'apple',
  'banana',
  123123,
  false,
  'mango',
  [ 1, 2, 3 ],
  {
    foo: 'bar',
    colors: { apple: 'red', banana: 'yellow', mango: 'green' },
    empty: null,
  },
  ...(new Array(72).fill('apple')),
]
let data = data1
$: _data = JSON.stringify(data, null)

function toktok(key)
{
  switch (key) {
    case 1:
      data = data1
      break
    case 2:
      data = data2
      break
    case 3:
      switch (theme)
      {
        case 'system':
          theme = 'light'
          break
        case 'light':
          theme = 'dark'
          break
        case 'dark':
          theme = 'system'
          break
      }
      break
  }
}

function exportData()
{
  const data = self.core.export(true, 2)
  console.log('exportData()', data)
}

onMount(() => {
  // define custom element
  if (customElements.get(elementName))
  {
    customElements.upgrade(self)
  }
  else
  {
    customElements.define(elementName, JsonEditor)
    self.addEventListener('update', (e) => {
      console.log('update json-editor', e.detail.data)
      data = e.detail.data
    })
  }
})
</script>

<style lang="scss">
@import './app';
</style>
